export default {
  UPDATE_USER : 'UPDATE_USER',
  ADD_USER: 'ADD_USER',
  ADD_RELATION: 'ADD_RELATION',
  REMOVE_RELATION: 'REMOVE_RELATION',
  GET_USER: 'GET_USER',

  USER_GETTED: 'USER_GETTED',
  RELATION_DELETED: 'RELATION_DELETED',
  RELATION_ADDED: 'RELATION_ADDED',
  USER_UPDATED: 'USER_UPDATED',
  USER_ADDED: 'USER_UPDATED'
}
